data_dir: /scratch/st-cdeboer-1/najmeh/GSC-2024-04-12/rawreads/

samples:
    A2:
        barcode: A2_R2.fastq.gz
        second: A2_R1.fastq.gz

index:
    A7: /scratch/st-cdeboer-1/najmeh/GSC-2024-04-12/rawreads/refernce
    A2: /scratch/st-cdeboer-1/najmeh/GSC-2024-04-12/rawreads/reflenti

upstream_len:
    A7: 0
    A2: 15

bc_len:
    A7: 20
    A2: 15

downstream_len:
    A7: 25
    A2: 0
